public class Sample
{
public sample()
{
System.out.println("This is sample constructor");
}
  public static void m1()
  {
    System.out.println("Welcome to Git hub tutorial");
  }

def ramu:
print(5+5) 

  public void add()
  {
      System.out.println("newly added method1");
  }

  public void sub()
  {
    System.out.println("newly added method2");
  }
  public static void main(String[] args)
  {
     m1();

     Sample s = new Sample();
    
      s.add();

     s.sub();
  }

}
